<?php
/**
 * Forkel Counter
 *
 * @category    Forkel
 * @package     Forkel_Counter
 * @copyright   Copyright (c) 2016 Tobias Forkel (http://www.tobiasforkel.de)
 * @license     http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<span class="forkel_counter">

    <?php if ($icon = $this->getData('icon')): ?>
        <span class="fa <?php echo $icon; ?>"></span>
    <?php endif; ?>

    <?php if ($prefix = $this->getData('prefix')): ?>
        <span class="prefix"><?php echo $prefix; ?></span>
    <?php endif; ?>

    <?php if ($numeric = $this->getNumeric()): ?>
        <span class="counter" data-from="<?php echo $this->getData('from'); ?>" data-to="<?php echo $numeric; ?>" data-time="<?php echo $this->getData('time'); ?>" data-delay="<?php echo $this->getData('delay'); ?>"><?php echo $numeric; ?></span>
    <?php endif; ?>

</span>

<span class="forkel_counter_alert">
    <span class="alert warning">
            <?php echo $this->__('Something is wrong. Probably jQuery is not loaded or has a conflict with another library.'); ?>
    </span>
</span>